Application Flow Changes
tamu-datathon-org/Ouroboros pull request #46
Opened 2020-10-10 22:15 UTC by phulsechinmay

* Added resume link to exported CSV
* Removed auto-email on acceptance
* Changed language on status page to not include RSVP

2020-10-10 23:16 UTC, danielabreo requested changes
I'm wondering if `instance.resume` is the correct way to access the URL or if we should do `instance.resume.url` like the example [here](https://docs.djangoproject.com/en/dev/topics/files/). Doesn't hurt to try either way.

2020-10-11 01:45 UTC, geooot approved these changes

2020-10-11 01:50 UTC, phulsechinmay commented
@danielabreo Good catch! Fixed it

2020-10-11 02:32 UTC, danielabreo approved these changes

2020-10-11 23:31 UTC, merged